### ISSUE TITLE
refactor crud update (patch) and write tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#107]
*As a* developer
*I need* to refactor the CRUD update (using PATCH HTTP verb) and write unit tests
*So that* the DB specific update logic is in the interface file and the unit tests make sure that only valid PATCH requests can update part of the payments in the DB.

**Assumptions**
- API Call: ` PATCH /payments/{payment_id}`
- requires JSON request body with any of the three updateable fields/attributes: nickname, payment_type, and details (all the fields)
- requires validation of the JSON request to check that only the updateable fields' values are updated - validation done in db/interface.py
- Currently, entire details has to be provided in the JSON request - PATCH requests for details will be supported in a future issue.
- tests written using PyUnit in tests/test_payments.py

**Acceptance Criteria**

Given a valid scenario
When there's a PATCH request with payment id = ID and a request to change, say nickname
Then (first the update-payments-partially function is invoked, which in turn invokes a semi-generic update method that directly interacts with the database) the payment with payment_id = ID with the requested changes to nickname must be displayed (and changed in the database) with HTTP_200_OK status code

**Comment by nvme5** [comment]
Covered in PR #126
