### ISSUE TITLE
refine delete test cases

### ISSUE THREAD

**Issue by nvme5** [devops-s17-payments/payments#133]
*As a* developer
*I need* to refactor existing test case and add some more test cases for deleting a payment
*So that* anytime remove_payment is called I can be sure that my code does the needful

**Assumptions**
- updating existing test cases
- new test cases will not use mock and will check for the count before and after deletion

**Acceptance Criteria**
```
*Given* that I want to delete an existing payment
*When* I call the remove_payments with a valid id
*Then* the payment with that id should have is_removed = True 
and the count of the payments should be one less
```
```
*Given* that I want to delete an non-existing payment
*When* I call the remove_payments with an invalid id
*Then* there should be no error and the count of the payments should remain the same
```

**Comment by jdgumz** [comment]
Should we close this guy?  Might need more specific details for this story to be actionable.

**Comment by nvme5** [comment]
I wanted to update the delete test case to check the count, and add some mock asserts
