### ISSUE TITLE
write test cases for is_valid_put method

### ISSUE THREAD

**Issue by nvme5** [devops-s17-payments/payments#135]
*As a* developer
*I need* to write test cases for is_valid_put method
*So that* I can make sure that the is_valid_put method does all validations and can increase my test coverage

**Assumptions**

**Acceptance Criteria**

*Given* ...
*When* ...
*Then* ...

**Comment by nvme5** [comment]
Duplicate issue of #87

**Comment by odoric27** [comment]
closing duplicate
