### ISSUE TITLE
write bdd feature for read

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#140]
*As a* API developer
*I need* to simulate the customer's behaviour to read a single payment
*So that* I can see if my `GET /payments/<int:id>` API behaves as it is supposed to

**Assumptions**
- There is a template in place for the BDD testing
- The unit tests are in place and pass for the API and the corresponding db interface

**Acceptance Criteria**

```
*Given* a customer
*When* I want to get information about a particular (existing) payment 
*Then* I should see the information about that payment
```
```
*Given* a customer
*When* I want to get information about a particular (non-existing) payment 
*Then* I should see an error stating payment not found
```

**Comment by jdgumz** [comment]
Hmm, now that I think about it - isn't this story really a sub-story of doing a query?  The list story makes sense for showing a user's payment history all at once.  But for looking up a specific payment, that seems to imply querying...what are your thoughts?

**Comment by odoric27** [comment]
this makes sense, but I wonder if we should it include it anyway as the spec specifically requests a test for each CRUD + list, action, query. While the mechanics of the `GET /payments/1` are similar to `GET /payments?payment_type=Visa`, having both tests might make things clearer for grading purposes.

**Comment by nvme5** [comment]
Is this test for `GET /payments` or `GET /payments/1` ?

**Comment by odoric27** [comment]
@nvme5 this should be `GET /payments/1` whereas `GET /payments` would be handled in the list ticket.

some of this functionality is already utilized in other steps so you can expand upon those and include some "sad path" scenarios
