### ISSUE TITLE
write bdd feature for list

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#143]
*As a* customer
*I need* to see all of my payments
*So that* I can track my expenditures

**Acceptance Criteria**
```
Given a customer on the eCommerce site
When they access their payments / click on "My Payments"
Then they should see all payments in their payment history, or nothing if that history does not yet exist
```

**Implementation Notes**
* The user action should correspond with a call to the db interface that makes use of the user's id in order to find all of the payments.
* The list might need to be sorted a certain way, unless SQLAlchemy returns objects in order of recency.

**Comment by jdgumz** [comment]
The ticket's wording is meant to appeal to a general use case for the API and also the specific case of using our API via a web site's UI.
