### ISSUE TITLE
write bdd feature for single query (good and bad)

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#144]
*As a* API developer
*I need* to simulate the customer's behavior to query in payments using a single attribute
*So that* I can see if my `GET /payments?<attr>=<value>` API behaves as it is supposed to

**Assumptions**
- There is a template in place for the BDD testing
- The unit tests are in place and pass for the API and the corresponding db interface
- Only the attributes of 'payment' are queried for and not the nested 'details'

**Acceptance Criteria**
```
*Given* a customer
*When* I query payments with a valid query 
*Then* I should see the information about that payment that matched the query
```
```
*Given* a customer
*When* I query payments with a bad query (i.e. query resulted in no results)
*Then* I should see an error stating 'Requested resource(s) could not be found'
```

**Comment by jdgumz** [comment]
This one could very quickly blow up in scope if we consider all possible combinations of queries - ones with only a single parameter, ones with two parameters, etc.  Should we break this ticket into specific queries that we expect to happen more often?

**Comment by odoric27** [comment]
yeah, that's a good point. then there's also the "sub-query" or whatever you want to call it, which isn't even supported at present. this would be a query for specific details of a payment method (i.e.; card_type=Visa}

so yes, i think we should break this up into smaller stories.

**Comment by odoric27** [comment]
per comments, turning this into single query feature for good and bad requests

**Comment by odoric27** [comment]
@nvme5 could you feel out the AC before you merge? thanks!
