### ISSUE TITLE
write simple UI to facilitate selenium testing

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#148]
this needs to be discussed a bit more, but per the assignment spec, we do need something simple.
just a couple forms for adding/updating/deleting, etc.

in thinking about forms, makes me wonder how much we really need to care about PATCH. When editing a form, you're usually presented with all possible fields. Even if you only update one, the form request probably sends all the data back anyway. Furthermore, as PATCH is not required by the assignment spec, I don't think we should be overly concerned with supporting it anymore than we do.

*As a* ...
*I need* ...
*So that* ...

**Assumptions**
...

**Acceptance Criteria**
...

*Given* ...
*When* ...
*Then* ...

**Comment by jdgumz** [comment]
We should decide whether or not we need to add a way to "authenticate", as in, a way for only one user to see information relevant to them.  Otherwise we can just build a test UI that takes a user id as a form of authentication.  It's sort of awkward but it could suit our purposes.

**Comment by odoric27** [comment]
makes sense. anything else might open a can of worms. i was thinking about support a login feature, but saving those credentials requires some extra db work, expanding the model and/r or writing a new one.

so agreed on a simple login via ID only

**Comment by odoric27** [comment]
expanding my thoughts on this...

assuming a single page layout, how best to handle requests like POST/PUT requiring user input? i know we're sticking json behind the scenes, but perhaps some forms on the front end make sense for ease of input ( and as also serve as a more realistic model of how the UI would actually be).

a quick search revealed some ways to convert form data into json so we can pipe it into the API the same as before. I like this idea, but haven't dived into the particulars yet. here's one blog outlining an approach, but maybe there's something baked into flask that will be a better fit (https://code.lengstorf.com/get-form-values-as-json/).

Furthermore, with respect to something like PUT: i guess if there's an UPDATE button, it would need to take an id signifying that which is to be updated. From there, would the results window display forms that have been auto-filled with the existing payments values so the user can pick and choose what they want to update?

while this makes sense in principle, seems to violate the role of the "results" window which in my mind is more akin to console ouput and all in json format. if sticking to single page, maybe there's a "working window" that takes data via forms for these POST/PUT requests and then outputs everything in the results window?

stop me at anytime if/when this sounds like nonsense. let me know what you think.

**Comment by odoric27** [comment]
one other thought... might be nice to provide a means for the a logged-in user to have the user_id they provided be automatically inserted into POST requests so that new cards automatically get assigned to them.

i guess we could pull this out of a cookie? haven't explored cookies/session state in flask, but i'm sure it's not too difficult to pass that info around and use as needed. anyone have any thoughts on this or an approach that might work better?

**Comment by odoric27** [comment]
so... this isn't required. i'd say this can move to the icebox. should we have time to tackle it, i'm all for it, but it shouldn't block other required items from getting done.

what do you think @jdgumz @nvme5 @SharanyaT ?

**Comment by SharanyaT** [comment]
I agree @odoric27, we can first focus on what's important and definitely required immediately

**Comment by nvme5** [comment]
Me too, let's put this in icebox and work on it in the next sprint if we have the bandwidth
