### ISSUE TITLE
Docker stuff

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#189]
update this after docker lecture.
need one for dev with link to postgres images
need another for prod bound to postgres service (elephantsql)

- update vagrantfile to include docker install and bluemix config
- uncomment postgres docker image pulls
- add dockerfile
- add docker-compose.yml

**Comment by odoric27** [comment]
@jdgumz i forgot that i started a small branch on this during lecture last week. i just pushed up the branch if any of it proves useful to you. didn't do much on it so it'll save you all of three minutes, but thought i'd share anyway.

branch is called `docker-prereqs`

i know i've dealt the most of the postgres beast so happy to lend a hand on this if you need or help troubleshoot, etc.

as a side note, probably doesn't matter much in the end, but i thought we might keep db live on VM as a second failover in case (i) not on bluemix and (ii) docker fails for some reason

**Comment by jdgumz** [comment]
@odoric27 If a docker container fails, then we'll just launch another one :)

**Comment by jdgumz** [comment]
I think I'm getting close to the finish line with this one.  @odoric27 we cannot run the postgres instance on the VM in the background since there will be port contention for 5432.  We could use different ports, but that's a bit messier to manage.

**Comment by odoric27** [comment]
ah, right. makes sense.
