### ISSUE TITLE
coverage vs codecov discrepancy

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#195]
coverage report indicated 99% coverage
codecov says 78%

need to investigate the discrepancy

**check out:**
https://docs.codecov.io/docs/ignoring-paths

**and consider:**
writing additional tests to cover some of the smaller config files to bridge the coverage gap

**Comment by nvme5** [comment]
codecov now ignores config.py and tests/features/*
However, the coverage is still at 82% because of models.py

**Comment by odoric27** [comment]
@nvme5 is this still in progress or good to close?

**Comment by nvme5** [comment]
I've just kept it open in case you - @odoric27 or @jdgumz want to take a look as to why models.py is showing the incorrect coverage.

**Comment by odoric27** [comment]
that's gonna be pass from me. i've got too much else to do :/

thanks though. it does bother me a little bit that the coverage is so
screwy.
