### ISSUE TITLE
Modify add payment method to allow json arguments

### ISSUE THREAD

**Issue by wenhaolu93** [devops-s17-payments/payments#39]
As a uesr
I need to pass json aruments to add payment method
So that new data can be passed by json into the memory(later in database)

Assumptions
new data is stored in samplePostData.json for test purpose

Acceptance Criteria
When issuing POST on http://localhost:5000/payments with argument (data in samplePostData.json), the data should be added in memory and can behave accordingly br CRUD methods.

**Comment by odoric27** [comment]
looks good. merged the PR.
