### ISSUE TITLE
Fine-tune update function so accept only those attributes being changed

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#59]
*As a* User
*I need* a way to change one or more attributes
*So that* my payment methods are always up to date

**Assumptions**
* users should be able to provide only those attributes they wish to change instead of the entire payment object with updated fields where appropriate

**Acceptance Criteria**

*Given* an existing payment method with id=1 with name = 'John Johnson'
*When* I issue PUT request with json object in requesy body = {'name' = 'Sally Smith'}
*Then* when I GET /payments/1 I should see name : 'Sally Smith'

**Comment by odoric27** [comment]
@wenhaolu93 been reviewing slides for midterm and just realized that my proposal for this story may be flawed. PUT is meant to replace an existing resource in full (as we currently implement) whereas PATCH is meant to update specific attributes of an existing resource. This story might make us less RESTful then we want to be for purposes of the assignment.

Perhaps we should reconsider this issue... what do you think?

**Comment by wenhaolu93** [comment]
@odoric27 I think you are right. I found out that PATCH may not be idempodent in some cases and can make our service less RESTful. What I am doing is creating another PATCH method with ability to partially update and keep the original PUT method unchanged.
