### ISSUE TITLE
need ability to "update payment-method"

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#6]
As a _User_
I need to update the payment methods(may be name, card number, address..)
So that i can use the new payment method to pay for my orders

_Assumptions_
*use decorator: @app.route('/payments/id', methods=['PUT'])
[I think maybe we need to add an attribute '_id_' in our payment object]

Will need to add to redis DB eventually, but can use local memory for now

_Acceptance Criteria_

Given several existing payment methods
When I GET _/payments_
I should see some payment methods(with the old information) in the list
And if I issue PUT _/payments/id_
Then the corresponding payment information should be updated
When I issue GET _/payments_
I should see the payment methods with new information in list of payment-methods

**Comment by yangyangiscoding** [comment]
#35
