### ISSUE TITLE
db services 'update_payments' and tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#85]
*As a* developer
*I need* to be able to update payments using a single method in the persistence layer
*So that* I can update entire or partial payments using just one method.

**Assumptions**
- update_payment requires a JSON request body 
- JSON request can either be complete request(PUT) or a partial request (PATCH).
- Validations are done for both PUT and PATCH requests
- This only caters to PUT and PATCH update requests and not the actions (set-default and charge - these are also patch updates but will be taken care of by another method in the interface.py)

**Acceptance Criteria**

Given a valid scenario
When there's a PUT/PATCH request with payment id = ID and a request with change to say nickname
Then (a semi-generic update method that directly interacts with the database is invoked) and changes the specified fields for payment module with payment_id = ID

**Comment by nvme5** [comment]
covered in PR #126

**Comment by SharanyaT** [comment]
Some interface tests are pending - will raise a PR soon, Moving back to in progress
