### ISSUE TITLE
Remove persistence logic from CRUD methods

### ISSUE THREAD

**Issue by jdgumz** [devops-s17-payments/payments#88]
*As a* payments developer
*I need* to decouple database and persistence logic from CRUD methods
*So that* I can more easily test CRUD operations and persistence operations

**Assumptions**
Existing persistence logic (i.e., changes to data entries in a database) can be
ported to a separate module with its own suite of methods.

**Acceptance Criteria**
All persistence or database-related operations are wrapped up in methods which are
called as needed by CRUD methods.

*Given* ...
*When* ...
*Then* ...

**Comment by odoric27** [comment]
does it make sense to break this story up a bit? maybe writing unit tests for each function should include refactoring each function to pull this logic out into new persistence module.

this will make merges a big messier, but i think this may allow us to fully develop our tests and not rely on or wait for someone else's work w/r/t implementing this new layer.

**Comment by jdgumz** [comment]
@odoric27 I hear what you're saying, but I worry about the alternative of putting non-unit test work into the unit test stories.  Still, your point is well taken and I think we should split this guy apart.

What we might be able to do is split up the work by operation.  For instance, there should be interface methods for all database operations: get_payments, remove_payments, add_payments, update_payments, etc.  Maybe each method could be its own ticket.  Part of the AC for the ticket would be a unit test of the operation - I think that's a reasonable criterion (part of the whole "if you add code, add tests too").

As for the unit testing of the CRUD operations, we can actually write those tests without having the db layer fully implemented.  What we can do is come up with the db interface methods and their signatures, and then replace the corresponding code in the CRUD method with that operation.

For example:

```
@app.route('/payments', methods=['GET'])
def list_payments():
	if request.query_string != "":
		results = db.get_payments(**request.args)
	type = request.args.get('type')
	if type:
		results = db.get_payments(type=type)
        else:
		results = db.get_payments()

	return make_response(jsonify(results), HTTP_200_OK)
```

To explain:
* `get_payments` will be able to take a variable number of **kwargs (keyword arguments), a named keyword "type" that has some special significance, or no arguments at all which would suggest that all payments should be returned.
* Unit testing might seem unintuitive here since the actual `db.get_payments` method may not exist yet, but consider the following:
  * The ideal unit test for this CRUD operation only tests `list_payments` - it should *not* test the behavior of `db.get_payments`.
  * Hence, we will be mocking all method calls inside the CRUD operations in order to test the behavior of the CRUD operation itself.  We can set the return value(s) of the different `db.operation` calls to whatever we want depending on the test case at hand.

An example mock for the test:
```
from mock import patch

def test_list_payments():
    with patch.object(db, 'get_payments', return_value=all_payments_data) as mocked_get_payments:
        # taking some liberties here - assume that the list_payments call gets the appropriate request info
        results = list_payments()
        # the actual keys might be different, this is just pseudocode
        assert results['code'] == HTTP_STATUS_OK
        assert results['data'] == mocked_get_payments.return_value
```

To explain:
* We mocked the `get_payments` method of the db object so that it would return some dataset.
* This test case is looking to check that the `list_payments` method returns the exact same data as what is returned by the mocked call to `get_payments`.  This is the case where no query parameters or type parameter are supplied (i.e., get all payments data).

**Suggested path forward**
* Write a story which is really just us coming up with an acceptable set of database methods.  Once we have consensus on those, we can easily divvy up the work of either implementing the methods themselves or refactoring the CRUD methods to use them (even if their implementations do not yet exist).
* Writing unit tests will go hand in hand with the affected code.  If you're refactoring the CRUD method, then the unit tests you write will be for that CRUD method.  If you're implementing a database method, then the unit tests will be for that database method.

**Comment by odoric27** [comment]
@jdgumz this is great. thanks for the thorough explanation. a clarifying question, just so i'm on the same page. in this instance then, our mock data of `all_payments_data` noted above is a dict ofdummy data we provide for purposes of the test? i guess something defined in our setup function?

and `results` contains data from the current implementation of list_payments, which ideally should return the same data as the mocked `get_payments` despite not implementing it yet?

i'll add more to the brainstorm issue #95 as well w/r/t required functions

**Comment by odoric27** [comment]
closing this issue since it's been broken up into smaller issues
