### ISSUE TITLE
refactor query and write tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#90]
*As a* developer
*I need* to test my queries
*So that* bad/malicious queries are handled accordingly and good queries return the correct data

**Assumptions**
* using PyUnit

**Acceptance Criteria**

*Given* an illegal query `not-a-key=bad-value`
*When* I issue `GET /payments?not-a-key=bad-value`
*Then* the test should find that a (400) status code is returned with an informative message

*Given* an legal query `/payments?type=credit`
*When* I issue `GET /payments?type=credit`
*Then* I should get all payments of type 'credit' with (200) status code

**Comment by jdgumz** [comment]
We will place the refactored query method inside the `PaymentService` class so that it can be used internally.
