### ISSUE TITLE
refactor list and write tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#91]
*As a* ...
*I need* ...
*So that* ...

**Assumptions**
...

**Acceptance Criteria**
...

*Given* ...
*When* ...
*Then* ...

**Comment by jdgumz** [comment]
This is actually part of #120 - sorry, should have realized that there were separate tickets.
Should we just move this issue alongside #120 , @odoric27 ?

**Comment by odoric27** [comment]
Theyre pretty closely related so makes sense to combine. Thanks!

On Apr 3, 2017 8:36 PM, "Jesse Gumz" <notifications@github.com> wrote:

This is actually part of #120
<https://github.com/devops-s17-payments/payments/pull/120> - sorry, should
have realized that there were separate tickets.
Should we just move this issue alongside #120
<https://github.com/devops-s17-payments/payments/pull/120> , @odoric27
<https://github.com/odoric27> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/devops-s17-payments/payments/issues/91#issuecomment-291345353>,
or mute the thread

**Comment by odoric27** [comment]
moving this out of backlog to avoid any confusion

**Comment by odoric27** [comment]
closed by #120
