### ISSUE TITLE
refactor 'set-default' action and write tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#92]
*As a* developer
*I need* to refactor the set-default action and write tests for this action
*So that* the db specific code is in the interface file and the unit test for set-default action checks that the particular payment for a user is set to default and any other previously default payment for that user are set to false.

**Assumptions**
- set-default action uses PATCH so only the 'is-default' attribute of that payment type is updated to True
- the set-default action API doesn't accept a JSON request body
- the set-default method in payments.py will use the payment_action method in the interface.py
- the 'is-default' can already be set to true or false for any payment for a user
- unit tests are written using PyUnit

**Acceptance Criteria**

```
*Given* a happy scenario
*When* I call PATCH /payments/{id}/set-default
*Then* payment with that id should have default: True and
     other payments for the user id same as the user with payment id {id} should be default: False
```

```
*Given* an illegal scenario
*When* I call PATCH /payments/{id}/set-default where the payment with {id} does not exist
*Then* it should raise a 404, payment not found error
```

**Comment by nvme5** [comment]
This API will now be : `PATCH /payments/<int:user_id>/set-default` With JSON request body having {payment_id: <payment_id}
