### ISSUE TITLE
refactor 'charge' action and write tests

### ISSUE THREAD

**Issue by odoric27** [devops-s17-payments/payments#93]
*As a* developer
*I need* refactor charge action and write unit tests for it
*So that* db specific code is in the interface file and the unit-tests make sure only the default payment is charged

**Assumptions**
- this is a PATCH update
- requires a JSON request body with the charge amount
- charge_history is updated with the existing amount and the charge amount from the request
- the charge method in payments.py will use the payment_action method in the interface.py
- validation of default payment will be done in the interface.py
- validation of the charge amount will be done in payments.py before calling the db service

**Acceptance Criteria**
```
*Given* a valid scenario
*When* I call 'PATCH /payments/charge'
*Then* if it is the default payment for that user, charge_history will be updated with the amount
```

**Comment by nvme5** [comment]
This API will now be : `PATCH /payments/<int:user_id>/charge` With JSON request body having {amount:<charge_amount>}
